### ISSUE TITLE
Refine formatting of bill names

### ISSUE THREAD

**Issue by jhoerr** [jhoerr/iga-tracker-web#1]
In general we want bill names to be formatted with:
1. a space between the chamber specifier and bill number, and
2. leading zeroes removed from the bill number.

| Original | Formatted |
| -------- |:-----------:|
| `SB0029` | `SB 29` |
| `HB1004` | `HB 1004` |

**Comment by ohnoitsaustin** [comment]
snuck a fix for this in to https://github.com/jhoerr/iga-tracker-web/commit/228d181b914cddf1f41fbd36224f3c4bca675ce4
