### ISSUE TITLE
Account-related configuration options

### ISSUE THREAD

**Issue by jhoerr** [jhoerr/iga-tracker-web#13]
As a user I want to be able to be able to configure the following on a per-account basis:

| | Email Address |
| --- | ---|
|*Type*| text|
|*Format*| email address|
|*Required*|no|
|*Descripton*|The email address at which I want to receive email alerts on bill activity.|
|*Default*|The email address of the FB/Google account with which I've logged in.|

| | Mobile Number |
| --- | ---|
|*Type*| text|
|*Format*| 9-digit phone number|
|*Required*|no|
|*Descripton*|The mobile number at which I want to receive SMS/text alerts on bill activity. (Normal messaging rates apply.)|
|*Default*|*none*|

| | **Daily Digest Type** |
|---|---|
|*Type*|radio|
|*Required*|no|
|*Description*| The kind of daily digest I wish to receive. This requires the presence of an alert email address. If an email address is not present this field should should be disabled with 'no digest' auto-selected.|
|Choices |<ul><li>activity of bills I'm tracking in this session (<-- default)</li><li>activity of all bills in this session</li><li>no digest</li></ul>|

**Comment by jhoerr** [comment]
One implicit thing here that should be made explicit: we want to allow for the possibility that a user might wish to receive no alerts and just want to track/view bill progress. That's why the email/mobile fields are optional.

I think we might also use the presence/absence of values in the email/mobile fields as a hint for which alerts they want to receive when tracking a bill. For example, if they have provided a mobile number but not an email, we should pre-select 'SMS' alerts by default when a bill is tracked.

**Comment by ohnoitsaustin** [comment]
These settings are up on test now, as is Google login. Let me know if there are any issues with them. 

still todo: add a migration to add a new column for alertEmail, and update that instead of the Email column, so that login still works if you change your email.

Will that mean updating The Functions to send to there instead? Would it be better to add an authProviderEmail column, and let the Email column be used as it currently is?

**Comment by jhoerr** [comment]
It would be least disruptive to add an `authProviderEmail` column, and allow the user to modify the 'Email' column.

**Comment by ohnoitsaustin** [comment]
That's now added on test. The migration will take care of copying the current Email column to the new AuthProviderEmail column, so there shouldn't be any disruption of existing accounts.
