### ISSUE TITLE
Search should be case-insensitive

### ISSUE THREAD

**Issue by jhoerr** [jhoerr/iga-tracker-web#15]
Search appears to be case-sensitive at the moment. To reproduce:

1. Browse to All Bills
2. Search for "gasohol". Observe that several bills are found.
3. Search for "Gasohol". Observe that no bills are found.

**Comment by ohnoitsaustin** [comment]
fixed in https://github.com/jhoerr/iga-tracker-web/commit/762cc63c7e2c9c8c142605c397237df35ea3e573
