### ISSUE TITLE
Account settings success message

### ISSUE THREAD

**Issue by ohnoitsaustin** [jhoerr/iga-tracker-web#19]
The account settings page does not indicate that the settings were successfully saved. To reproduce:

1. Log in and go to your account settings by clicking your name in the header
2. Change something, like your email
3. Click "Submit"
4. Be confused. Did it save? Who knows!

**Comment by jhoerr** [comment]
We might consider having this send a confirmation email and/or confirmation text. My mom joined today (thanks mom!) and she said she didnt know if she "did it right" because she didnt get any sort of confirmation. The confirmation email might also include info/links for how to use the service.
