### ISSUE TITLE
www.pingthepeople.com should redirect to pingthepeople.com

### ISSUE THREAD

**Issue by jhoerr** [jhoerr/iga-tracker-web#23]
Lotsa folks are used to typing "www." in front of web addresses, so we should gracefully redirect them to the proper hosted domain. I've already set up DNS records to point _www._ to the our host, as well as host bindings to receive requests at that domain. We just need an HTTP rewrite rule to perform the actual redirect.

**Comment by ohnoitsaustin** [comment]
looks like this is working correctly. FWIW, I think only the web.config redirect was needed; .htaccess only applies to apache servers.
