### ISSUE TITLE
Intro / splash screen

### ISSUE THREAD

**Issue by jhoerr** [jhoerr/iga-tracker-web#25]
It'd be nice to have a splash screen that describes the value of Ping the People. I'm thinking we could generally break this up into three sections:

1. Discover legislation 

![search](https://cloud.githubusercontent.com/assets/1151206/24211803/8e969fa4-0f03-11e7-9f11-f21f15e32672.PNG)

2. View status of legislation

![watch](https://cloud.githubusercontent.com/assets/1151206/24211816/976f4004-0f03-11e7-95b6-c4a825731655.PNG)

3. Get instant alerts

![alert_email](https://cloud.githubusercontent.com/assets/1151206/24211852/b445fa9c-0f03-11e7-98b4-862b23e906bc.PNG)

![alert_text](https://cloud.githubusercontent.com/assets/1151206/24211861/b9dd4e9c-0f03-11e7-99d5-3e0e6c3eee55.png)

**Comment by ohnoitsaustin** [comment]
resolved with #34
