### ISSUE TITLE
As a user browsing All Legislation, I only want to see legislation that is not dead unless I indicate otherwise

### ISSUE THREAD

**Issue by jhoerr** [jhoerr/iga-tracker-web#28]

**Comment by ohnoitsaustin** [comment]
Now that the 'Dead' tag is implemented, does this still sound like a good idea? Or is it better to display everything by default?

**Comment by jhoerr** [comment]
I think lets keep showing everything until folks ask for otherwise.

--
John Hoerr (mobile)
503.360.6581
