### ISSUE TITLE
Email / SMS selections not remembered

### ISSUE THREAD

**Issue by jhoerr** [jhoerr/iga-tracker-web#6]
Email / SMS alert checkbox selections are not remembered. To reproduce:

1. Ensure you are tracking at least one bill
2. Browse to My Bills view
3. Uncheck Email or SMS alert checkbox
4. Refresh page
5. Observe that checkbox state has reverted to checked.

**Comment by ohnoitsaustin** [comment]
fixed in https://github.com/jhoerr/iga-tracker-web/commit/a93f34bdc35919e1abbdaa84081f77379cf85c69
