### ISSUE TITLE
"Track <Bill Number>" button has wrong state

### ISSUE THREAD

**Issue by jhoerr** [jhoerr/iga-tracker-web#8]
The track button shows "Track <Bill Number>" for bills that are already being tracked. To reproduce:

1. Browse to the All Bills view
2. Click "Track <Bill Number>" to track any bill.
3. Reload the page. 
4. Observe that the button continues to read "Track <Bill Number>"

**Comment by ohnoitsaustin** [comment]
fixed in https://github.com/jhoerr/iga-tracker-web/commit/a93f34bdc35919e1abbdaa84081f77379cf85c69
